name: oeln
favicon: null
layout_spectrum: 0.15607672231271863
typography_spectrum: 0.8638038337230682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.26180127332918346
  lightness: 0.0216933221090585
  saturation: 0.281698094913736
  rhythmicContrast: 0.3731982468161732
purpose: []
