favicon: null
name: oeln
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.281698094913736
  brandStrength: 0.2618012733291835
  lightness: 0.0216933221090585
  brandColors:
    - '#F4F3F1'
    - '#9B9988'
    - '#787664'
  rhythmicContrast: 0.3731982468161732
typography_spectrum: 0.9367622
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
